version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk update 
            apk upgrade 
            apk add build-base
            apk add cmake
            apk add curl
      - sonarcloud/scan
      - run:
          name: Build and run
          command: |
            mkdir build
            cd build
            cmake ..
            ./chip8



orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  cpp-workflow:
    jobs:
      - build:
          context: SonarCloud