version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          name: Build cmake
          command: |
            apk add build-base |
            apk add cmake
workflows:
  cpp-workflow:
    jobs:
      - build