version: 2.1
executors:
  ubuntu:
    docker:
      - image: ubuntu:18.04
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD

jobs:
  build_run:
    executor: ubuntu
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt update 
            apt upgrade -y 
            apt install -y build-essential
            apt install -y cmake 
            apt install -y python3
            apt install -y python-is-python3
            apt install -y python3-pip
            pip install conan
            mkdir project
      - run:
          name: Build
          command: |
            cd project
            mkdir build
            cd build
            conan install .. --build=missing
            cmake ..
      - run:
          name: Run
          command: |
            cd project
            cd build
            cmake --build .
            ./chip8

workflows:
  version: 2
  cpp-workflow:
    jobs:
      - build_run