version: 2.1
executors:
  ubuntu:
    docker:
      - image: ubuntu:18.04
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD

jobs:
  build_run:
    executor: ubuntu
    environment:
      DISPLAY: :99
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt update 
            apt upgrade -y 
            apt install -y build-essential
            apt install -y cmake 
            apt install -y python3
            apt install -y python3-pip
            apt install -y libegl1-mesa-dev
            apt install -y libsdl2-dev
            pip3 install conan
      - run:
          name: Build
          command: |
            mkdir build
            cd build
            conan profile new default --detect
            conan profile update settings.compiler.libcxx=libstdc++11 default
            conan install .. --build=missing -c tools.system.package_manager:mode=install
            cmake ..
      - run: sudo apt-get update -qq && sudo apt-get install -y -qq xvfb
      - run:
          command: Xvfb -ac :99 -screen 0 800x600x16 +extension RANDR
          background: true
      - run:
          name: Run
          command: |
            cd build
            cmake --build .
            ./bin/chip8

workflows:
  version: 2
  cpp-workflow:
    jobs:
      - build_run