version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:18.04
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt update 
            apt upgrade -y 
            apt install -y build-essential
            apt install -y cmake 
            apt install -y curl
            apt install -y zip
            apt install -y unzip
      - run:
          name: Build and run
          command: |
            mkdir build
            cd build
            cmake ..
            ./chip8



orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  cpp-workflow:
    jobs:
      - build:
          context: SonarCloud