version: 2.1
executors:
  ubuntu:
    docker:
      - image: ubuntu:18.04
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD

jobs:
  install:
    executor: ubuntu
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt update 
            apt upgrade -y 
            apt install -y build-essential
            apt install -y cmake 
            mkdir project
  run:
    executor: ubuntu
    steps:
      - run:
          name: Build and run
          command: |
            mkdir build
            cd build
            cmake ..
            ./chip8

workflows:
  version: 2
  cpp-workflow:
    jobs:
      - install
      - run